version: "3"
services:
  app:
    build: ./app
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "33333:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      